### ISSUE TITLE
Extract mode for SCSS file, when processUrls is false.

### ISSUE THREAD

**Issue by khaiknievel** [swisnl/laravel-mix-svg-sprite#10]
## Detailed description

Extract mode for scss file is working when `mix.options({ processCssUrls: true })`. But it is not working when setting the processCssUrls is false.

## Context

Would like to use relative url on my css.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Node 14.4.0
* Mac OSX 10.11.6

```scss
// assets/styles/main.scss
body {
	background-image: url(../sprites/email.svg);
}
```

```js
// assets/scripts/main.js
/**
 * Requires all directives from subdirectories.
 * @param requireContext
 * @returns {*}
 */
function requireAll(requireContext) {
	return requireContext.keys().map(requireContext);
}

// Require all icons in the sprites folder.
requireAll(require.context('../../sprites', true, /\.svg$/))
```
```js
// webpack.mix.js
mix
	.options({ processCssUrls: false, })
	.sass('assets/styles/main.scss', 'styles')
	.js('assets/scripts/main.js', 'scripts')
	.svgSprite('assets/sprites', 'sprite.svg')
;
```

**Comment by JaZo** [comment]
Hi @khaiknievel, thanks for reporting this issue. Can you clarify what you mean with 'it is not working'? What would you expect and what happens instead? Do you have some example output?

**Comment by khaiknievel** [comment]
Hey, alrights.

The expected css result.
```css
body {
	background-image: url(sprite.svg#email);
}
```

The actual result.
```css
body {
    background-image: url(../sprites/email.svg);
}
```

**Comment by JaZo** [comment]
Thanks for the quick reply! Unfortunately that is expected behaviour. Setting `processCssUrls` to false disables processing of all urls in CSS files. These urls will not be processed by Webpack neither the SVG sprite loader.

>**processCssUrls**: Process/optimize relative stylesheet url()'s. By default, Webpack will automatically update these URLs, when relevant. If, however, your folder structure is already organized the way you want it, set this option to false to disable processing.
https://laravel-mix.com/docs/5.0/options

**Comment by khaiknievel** [comment]
I see... Dang it. Got you. Thanks. :)

**Comment by khaiknievel** [comment]
Just gonna leave this here. Ended up using [postcss-url](https://github.com/postcss/postcss-url). The goal was to use relative url and to be able to use the sprite from css.

`yarn add postcss-url --dev`

```js
// webpack.mix.js
mix
	.sass('assets/styles/main.scss', 'styles')
	.options({
		processCssUrls: false,
		postCss: [
			require('postcss-url')({
				filter: '**/sprites/*.svg',
				url: (asset) => {
					var file = new File(asset.absolutePath)
					return `../sprite.svg?id=${file.version()}#${file.segments.name}-usage`
				}
			})
		]
	})
	.svgSprite('assets/sprites', 'sprite.svg', { extract: true }, { plainSprite: false })
;
```

From
```css
body {
	background-image: url(../sprites/email.svg);
}
```

becomes

```css
body {
	background-image: url(../sprite.svg?id=hash#email-usage);
}
```

**Comment by JaZo** [comment]
That's an interesting approach! What happens to the hash for different icons? If I read this code correctly, every icon will have a different hash and thus URL causing the browser to download the same sprite several times. Is that correct?

E.g.
```css
body {
    background-image: url(../sprites/email.svg);
}
div {
    background-image: url(../sprites/phone.svg);
}
```
will become
```css
body {
    background-image: url(../sprite.svg?id=l1c845o5t7#email-usage);
}
div {
    background-image: url(../sprite.svg?id=qfuazwrmq9#phone-usage);
}
```
