### ISSUE TITLE
Sprite is created but extracted asset urls are transformed to system path instead of relative with hash id

### ISSUE THREAD

**Issue by reageek** [swisnl/laravel-mix-svg-sprite#14]
## Detailed description

When compiling with option of extract true; the expectation is that the compiled css asset urls for sprite assets resolve as the sprite file with sprite fragments identifiers for such file. Instead the a system path to the file is what is injected.

The expectations relates to https://github.com/JetBrains/svg-sprite-loader/tree/master/examples/extract-mode

#### Input (main.css)

```css
.logo {background: url('./logo.svg')}
```

#### Output (dist/main.css)

```css
.logo {background: url('sprite.svg#logo-usage')}
```

#### Input (assets/app.scss)
```css
.test {
    background-image: url('./badge-steam.svg');
}
```
#### Output (dist/styles/app.css)
```css
.test {
  background-image: url(//home/user/localsites/site/app/public/wp-content/themes/test/assets/badge-steam.svg);
}
```
#### Expected Output (dist/styles/app.css)
```css
.test {
  background-image: url(./sprite.svg#badge-steam);
}
```

## Configuration

```js
const mix = require("laravel-mix");
require("laravel-mix-svg-sprite");

/**
 * @see https://laravel-mix.com/docs/6.0/api
 * @see https://laravel-mix.com/extensions/svg-sprite
 * @see https://github.com/JetBrains/svg-sprite-loader/tree/master/examples/extract-mode
 */
mix
  .options({
    watchOptions: {
      ignored: /node_modules/,
    },
    processCssUrls: true,
    useRelativePaths: true,
    publicPath: "dist",
  })
  .sass("assets/styles/app.scss", "styles")
  .svgSprite("assets/svgs", "svg/sprite.svg", {
    extract: true,
  });

```

### Screenshot
![image](https://user-images.githubusercontent.com/5495292/135310783-547a4f9b-1246-45be-ac0a-817ec78a57b7.png)

## source
[test.zip](https://github.com/swisnl/laravel-mix-svg-sprite/files/7253601/test.zip)

## Env Info
node v16.9.0
npm 7.22.0
OS Arch Linux x86_64
Kernel 5.13.13-arch-1-1
